/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.util.Stack;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;

/**
 *
 * @author Ramky Abel
 */
public class StartGUI extends javax.swing.JFrame {

    /**
     * Creates new form StartGUI
     */
    public StartGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JLabel();
        caText = new javax.swing.JLabel();
        divText = new javax.swing.JLabel();
        mulText = new javax.swing.JLabel();
        minusText = new javax.swing.JLabel();
        sevenText = new javax.swing.JLabel();
        eightText = new javax.swing.JLabel();
        nineText = new javax.swing.JLabel();
        plusText = new javax.swing.JLabel();
        fourText = new javax.swing.JLabel();
        fiveText = new javax.swing.JLabel();
        sixText = new javax.swing.JLabel();
        oneText = new javax.swing.JLabel();
        twoText = new javax.swing.JLabel();
        threeText = new javax.swing.JLabel();
        equalText = new javax.swing.JLabel();
        zeroText = new javax.swing.JLabel();
        dotText = new javax.swing.JLabel();
        caButton = new javax.swing.JLabel();
        divButton = new javax.swing.JLabel();
        mulButton = new javax.swing.JLabel();
        minusButton = new javax.swing.JLabel();
        sevenButton = new javax.swing.JLabel();
        eightButton = new javax.swing.JLabel();
        nineButton = new javax.swing.JLabel();
        plusButton = new javax.swing.JLabel();
        fourButton = new javax.swing.JLabel();
        fiveButton = new javax.swing.JLabel();
        sixButton = new javax.swing.JLabel();
        oneButton = new javax.swing.JLabel();
        twoButton = new javax.swing.JLabel();
        threeButton = new javax.swing.JLabel();
        equalButton = new javax.swing.JLabel();
        zeroButton = new javax.swing.JLabel();
        dotButton = new javax.swing.JLabel();
        displayText = new javax.swing.JLabel();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("X");
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeButtonMouseReleased(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        caText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        caText.setForeground(new java.awt.Color(255, 255, 255));
        caText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        caText.setText("CA");
        getContentPane().add(caText, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 108, -1, -1));

        divText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        divText.setForeground(new java.awt.Color(255, 255, 255));
        divText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        divText.setText("/");
        getContentPane().add(divText, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 108, -1, -1));

        mulText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mulText.setForeground(new java.awt.Color(255, 255, 255));
        mulText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mulText.setText("X");
        getContentPane().add(mulText, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 108, -1, -1));

        minusText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        minusText.setForeground(new java.awt.Color(255, 255, 255));
        minusText.setText("-");
        getContentPane().add(minusText, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 107, -1, -1));

        sevenText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sevenText.setForeground(new java.awt.Color(255, 255, 255));
        sevenText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sevenText.setText("7");
        getContentPane().add(sevenText, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 157, -1, -1));

        eightText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        eightText.setForeground(new java.awt.Color(255, 255, 255));
        eightText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eightText.setText("8");
        getContentPane().add(eightText, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 157, -1, -1));

        nineText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nineText.setForeground(new java.awt.Color(255, 255, 255));
        nineText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nineText.setText("9");
        getContentPane().add(nineText, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 157, -1, -1));

        plusText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        plusText.setForeground(new java.awt.Color(255, 255, 255));
        plusText.setText("+");
        getContentPane().add(plusText, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 182, -1, -1));

        fourText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fourText.setForeground(new java.awt.Color(255, 255, 255));
        fourText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fourText.setText("4");
        getContentPane().add(fourText, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 207, -1, -1));

        fiveText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fiveText.setForeground(new java.awt.Color(255, 255, 255));
        fiveText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fiveText.setText("5");
        getContentPane().add(fiveText, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 207, -1, -1));

        sixText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sixText.setForeground(new java.awt.Color(255, 255, 255));
        sixText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sixText.setText("6");
        getContentPane().add(sixText, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 207, -1, -1));

        oneText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        oneText.setForeground(new java.awt.Color(255, 255, 255));
        oneText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oneText.setText("1");
        getContentPane().add(oneText, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 257, -1, -1));

        twoText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        twoText.setForeground(new java.awt.Color(255, 255, 255));
        twoText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        twoText.setText("2");
        getContentPane().add(twoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 257, -1, -1));

        threeText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        threeText.setForeground(new java.awt.Color(255, 255, 255));
        threeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        threeText.setText("3");
        getContentPane().add(threeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 257, -1, -1));

        equalText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        equalText.setForeground(new java.awt.Color(255, 255, 255));
        equalText.setText("=");
        getContentPane().add(equalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 281, -1, -1));

        zeroText.setForeground(new java.awt.Color(255, 255, 255));
        zeroText.setText("0");
        getContentPane().add(zeroText, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 307, -1, -1));

        dotText.setForeground(new java.awt.Color(255, 255, 255));
        dotText.setText(".");
        getContentPane().add(dotText, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 305, -1, -1));

        caButton.setForeground(new java.awt.Color(255, 255, 255));
        caButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        caButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                caButtonMouseMoved(evt);
            }
        });
        caButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                caButtonMouseReleased(evt);
            }
        });
        getContentPane().add(caButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 96, 50, 40));

        divButton.setForeground(new java.awt.Color(255, 255, 255));
        divButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        divButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                divButtonMouseMoved(evt);
            }
        });
        divButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                divButtonMouseReleased(evt);
            }
        });
        getContentPane().add(divButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 96, 50, 40));

        mulButton.setForeground(new java.awt.Color(255, 255, 255));
        mulButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mulButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mulButtonMouseMoved(evt);
            }
        });
        mulButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mulButtonMouseReleased(evt);
            }
        });
        getContentPane().add(mulButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 96, 50, 40));

        minusButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minusButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                minusButtonMouseMoved(evt);
            }
        });
        minusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minusButtonMouseReleased(evt);
            }
        });
        getContentPane().add(minusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 96, 50, 40));

        sevenButton.setForeground(new java.awt.Color(255, 255, 255));
        sevenButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sevenButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                sevenButtonMouseMoved(evt);
            }
        });
        sevenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sevenButtonMouseReleased(evt);
            }
        });
        getContentPane().add(sevenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 146, 50, 40));

        eightButton.setForeground(new java.awt.Color(255, 255, 255));
        eightButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eightButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                eightButtonMouseMoved(evt);
            }
        });
        eightButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                eightButtonMouseReleased(evt);
            }
        });
        getContentPane().add(eightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 146, 50, 40));

        nineButton.setForeground(new java.awt.Color(255, 255, 255));
        nineButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nineButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                nineButtonMouseMoved(evt);
            }
        });
        nineButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nineButtonMouseReleased(evt);
            }
        });
        getContentPane().add(nineButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 146, 50, 40));

        plusButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plusButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                plusButtonMouseMoved(evt);
            }
        });
        plusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                plusButtonMouseReleased(evt);
            }
        });
        getContentPane().add(plusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 146, 50, 90));

        fourButton.setForeground(new java.awt.Color(255, 255, 255));
        fourButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fourButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fourButtonMouseMoved(evt);
            }
        });
        fourButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fourButtonMouseReleased(evt);
            }
        });
        getContentPane().add(fourButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 196, 50, 40));

        fiveButton.setForeground(new java.awt.Color(255, 255, 255));
        fiveButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fiveButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fiveButtonMouseMoved(evt);
            }
        });
        fiveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fiveButtonMouseReleased(evt);
            }
        });
        getContentPane().add(fiveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 196, 50, 40));

        sixButton.setForeground(new java.awt.Color(255, 255, 255));
        sixButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sixButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                sixButtonMouseMoved(evt);
            }
        });
        sixButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sixButtonMouseReleased(evt);
            }
        });
        getContentPane().add(sixButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 196, 50, 40));

        oneButton.setForeground(new java.awt.Color(255, 255, 255));
        oneButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oneButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                oneButtonMouseMoved(evt);
            }
        });
        oneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                oneButtonMouseReleased(evt);
            }
        });
        getContentPane().add(oneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 246, 50, 40));

        twoButton.setForeground(new java.awt.Color(255, 255, 255));
        twoButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        twoButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                twoButtonMouseMoved(evt);
            }
        });
        twoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                twoButtonMouseReleased(evt);
            }
        });
        getContentPane().add(twoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 246, 50, 40));

        threeButton.setForeground(new java.awt.Color(255, 255, 255));
        threeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        threeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                threeButtonMouseMoved(evt);
            }
        });
        threeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                threeButtonMouseReleased(evt);
            }
        });
        getContentPane().add(threeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 246, 50, 40));

        equalButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equalButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                equalButtonMouseMoved(evt);
            }
        });
        equalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                equalButtonMouseReleased(evt);
            }
        });
        getContentPane().add(equalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 245, 50, 90));

        zeroButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zeroButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                zeroButtonMouseMoved(evt);
            }
        });
        zeroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                zeroButtonMouseReleased(evt);
            }
        });
        getContentPane().add(zeroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 296, 110, 40));

        dotButton.setForeground(new java.awt.Color(255, 255, 255));
        dotButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dotButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                dotButtonMouseMoved(evt);
            }
        });
        dotButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dotButtonMouseReleased(evt);
            }
        });
        getContentPane().add(dotButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 296, 50, 40));

        displayText.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        displayText.setForeground(new java.awt.Color(255, 255, 255));
        displayText.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        displayText.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                displayTextComponentHidden(evt);
            }
        });
        getContentPane().add(displayText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 260, 50));

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/CalcDesign.png"))); // NOI18N
        backGround.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                backGroundMouseMoved(evt);
            }
        });
        getContentPane().add(backGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 350));

        setSize(new java.awt.Dimension(300, 350));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void caButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caButtonMouseMoved
        // TODO add your handling code here:
        caButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons100.png")));
    }//GEN-LAST:event_caButtonMouseMoved

                                
    private void backGroundMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backGroundMouseMoved
        // TODO add your handling code here:
        caButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons70.png")));
        divButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons70.png")));
        dotButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons70.png")));
        eightButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons70.png")));
        equalButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/horsideButtons70.png")));
        fiveButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons70.png")));
        fourButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons70.png")));
        minusButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons70.png")));
        mulButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons70.png")));
        nineButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons70.png")));
        oneButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons70.png")));
        plusButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/horsideButtons70.png")));
        sevenButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons70.png")));
        sixButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons70.png")));
        threeButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons70.png")));
        twoButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons70.png")));
        zeroButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/versideButtons70.png")));
        
    }//GEN-LAST:event_backGroundMouseMoved

    private void divButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divButtonMouseMoved
        // TODO add your handling code here:
        divButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons100.png")));
    }//GEN-LAST:event_divButtonMouseMoved

    private void mulButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mulButtonMouseMoved
        // TODO add your handling code here:
        mulButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons100.png")));
    }//GEN-LAST:event_mulButtonMouseMoved

    private void minusButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusButtonMouseMoved
        // TODO add your handling code here:
        minusButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons100.png")));
    }//GEN-LAST:event_minusButtonMouseMoved

    private void sevenButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenButtonMouseMoved
        // TODO add your handling code here:
        sevenButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons100.png")));
    }//GEN-LAST:event_sevenButtonMouseMoved

    private void eightButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightButtonMouseMoved
        // TODO add your handling code here:
        eightButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons100.png")));
    }//GEN-LAST:event_eightButtonMouseMoved

    private void nineButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineButtonMouseMoved
        // TODO add your handling code here:
        nineButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons100.png")));      
    }//GEN-LAST:event_nineButtonMouseMoved

    private void plusButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusButtonMouseMoved
        // TODO add your handling code here:
        plusButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/horsideButtons100.png")));
    }//GEN-LAST:event_plusButtonMouseMoved

    private void fourButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourButtonMouseMoved
        // TODO add your handling code here:
        fourButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons100.png")));  
    }//GEN-LAST:event_fourButtonMouseMoved

    private void fiveButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveButtonMouseMoved
        // TODO add your handling code here:
        fiveButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons100.png")));  
    }//GEN-LAST:event_fiveButtonMouseMoved

    private void sixButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixButtonMouseMoved
        // TODO add your handling code here:
        sixButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons100.png")));  
    }//GEN-LAST:event_sixButtonMouseMoved

    private void oneButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneButtonMouseMoved
        // TODO add your handling code here:
        oneButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons100.png")));  
    }//GEN-LAST:event_oneButtonMouseMoved

    private void twoButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoButtonMouseMoved
        // TODO add your handling code here:
        twoButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons100.png")));  
    }//GEN-LAST:event_twoButtonMouseMoved

    private void threeButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeButtonMouseMoved
        // TODO add your handling code here:
        threeButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons100.png")));  
    }//GEN-LAST:event_threeButtonMouseMoved

    private void zeroButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroButtonMouseMoved
        // TODO add your handling code here:
        zeroButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/versideButtons100.png")));  
    }//GEN-LAST:event_zeroButtonMouseMoved

    private void dotButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dotButtonMouseMoved
        // TODO add your handling code here:
        dotButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/numButtons100.png")));  
    }//GEN-LAST:event_dotButtonMouseMoved

    private void equalButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalButtonMouseMoved
        // TODO add your handling code here:
        equalButton.setIcon (new javax.swing.ImageIcon (getClass ().getResource ("/AppPackage/horsideButtons100.png")));  
    }//GEN-LAST:event_equalButtonMouseMoved

    private void closeButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseReleased
        // TODO add your handling code here:
        System.exit (0);
    }//GEN-LAST:event_closeButtonMouseReleased

    private void displayTextComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_displayTextComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_displayTextComponentHidden

    private void zeroButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroButtonMouseReleased
        // TODO add your handling code here:
        String previousValue = displayText.getText () + "0";
        displayText.setText (previousValue);
    }//GEN-LAST:event_zeroButtonMouseReleased

    private void oneButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneButtonMouseReleased
        // TODO add your handling code here:
        String previousValue = displayText.getText () + "1";
        displayText.setText (previousValue);
    }//GEN-LAST:event_oneButtonMouseReleased

    private void twoButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoButtonMouseReleased
        // TODO add your handling code here:
        String previousValue = displayText.getText () + "2";
        displayText.setText (previousValue);
    }//GEN-LAST:event_twoButtonMouseReleased

    private void threeButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeButtonMouseReleased
        // TODO add your handling code here:
        String previousValue = displayText.getText () + "3";
        displayText.setText (previousValue);
    }//GEN-LAST:event_threeButtonMouseReleased

    private void fourButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourButtonMouseReleased
        // TODO add your handling code here:
        String previousValue = displayText.getText () + "4";
        displayText.setText (previousValue);
    }//GEN-LAST:event_fourButtonMouseReleased

    private void fiveButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveButtonMouseReleased
        // TODO add your handling code here:
        String previousValue = displayText.getText () + "5";
        displayText.setText (previousValue);
    }//GEN-LAST:event_fiveButtonMouseReleased

    private void sixButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixButtonMouseReleased
        // TODO add your handling code here:
        String previousValue = displayText.getText () + "6";
        displayText.setText (previousValue);
    }//GEN-LAST:event_sixButtonMouseReleased

    private void sevenButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenButtonMouseReleased
        // TODO add your handling code here:
        String previousValue = displayText.getText () + "7";
        displayText.setText (previousValue);
    }//GEN-LAST:event_sevenButtonMouseReleased

    private void eightButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightButtonMouseReleased
        // TODO add your handling code here:
        String previousValue = displayText.getText () + "8";
        displayText.setText (previousValue);
    }//GEN-LAST:event_eightButtonMouseReleased

    private void nineButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineButtonMouseReleased
        // TODO add your handling code here:
        String previousValue = displayText.getText () + "9";
        displayText.setText (previousValue);
    }//GEN-LAST:event_nineButtonMouseReleased

    private void divButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divButtonMouseReleased
        // TODO add your handling code here:
        String previousValue = displayText.getText () + "/";
        displayText.setText (previousValue);
    }//GEN-LAST:event_divButtonMouseReleased

    private void mulButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mulButtonMouseReleased
        // TODO add your handling code here:
        String previousValue = displayText.getText () + "*";
        displayText.setText (previousValue);
    }//GEN-LAST:event_mulButtonMouseReleased

    private void minusButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusButtonMouseReleased
        // TODO add your handling code here:
        String previousValue = displayText.getText () + "-";
        displayText.setText (previousValue);
    }//GEN-LAST:event_minusButtonMouseReleased

    private void plusButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusButtonMouseReleased
        // TODO add your handling code here:
        String previousValue = displayText.getText () + "+";
        displayText.setText (previousValue);
    }//GEN-LAST:event_plusButtonMouseReleased

    private void caButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caButtonMouseReleased
        // TODO add your handling code here:
        displayText.setText ("");
    }//GEN-LAST:event_caButtonMouseReleased

    private void equalButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalButtonMouseReleased
        // TODO add your handling code here:

        Stack <Integer> numMain = new Stack <> ();
        Stack <Integer> tempNum = new Stack <> ();
        boolean doMult = false;
        Stack <Character> signMain = new Stack <> ();

        int result = 0;
        String exp = displayText.getText();


        for (int i = 0; i < exp.length (); i++)
        {
            if (Character.isDigit (exp.charAt (i)))
            {
                tempNum.add (exp.charAt (i) - '0');
            }
            else 
            {
                convTempNum (tempNum, numMain);
                if (doMult)
                {
                    mulAndDiv (numMain, signMain);
                    doMult = false;
                }
                signMain.add (exp.charAt (i));

                if (exp.charAt (i) == '*' || exp.charAt (i) 
                        == '/')
                    doMult = true;
            }
            if (!signMain.isEmpty () && i + 1 == exp.length ())
            {
                    convTempNum (tempNum, numMain);
                    if (doMult)
                            mulAndDiv (numMain, signMain);
            }
        }

        if (!tempNum.isEmpty ())
        {
                System.out.println ('y');

                convTempNum (tempNum, numMain);
        }
        if (!signMain.isEmpty ())
        {
                System.out.println ("hello???");
                sumsAndSubs (numMain, signMain);
        }

                result = numMain.pop ();

        displayText.setText (Integer.toString (result));

    }//GEN-LAST:event_equalButtonMouseReleased

    private void dotButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dotButtonMouseReleased
        // TODO add your handling code here:
        String previousValue = displayText.getText () + ".";
        displayText.setText (previousValue);
    }//GEN-LAST:event_dotButtonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JLabel caButton;
    private javax.swing.JLabel caText;
    private javax.swing.JLabel closeButton;
    private javax.swing.JLabel displayText;
    private javax.swing.JLabel divButton;
    private javax.swing.JLabel divText;
    private javax.swing.JLabel dotButton;
    private javax.swing.JLabel dotText;
    private javax.swing.JLabel eightButton;
    private javax.swing.JLabel eightText;
    private javax.swing.JLabel equalButton;
    private javax.swing.JLabel equalText;
    private javax.swing.JLabel fiveButton;
    private javax.swing.JLabel fiveText;
    private javax.swing.JLabel fourButton;
    private javax.swing.JLabel fourText;
    private javax.swing.JLabel minusButton;
    private javax.swing.JLabel minusText;
    private javax.swing.JLabel mulButton;
    private javax.swing.JLabel mulText;
    private javax.swing.JLabel nineButton;
    private javax.swing.JLabel nineText;
    private javax.swing.JLabel oneButton;
    private javax.swing.JLabel oneText;
    private javax.swing.JLabel plusButton;
    private javax.swing.JLabel plusText;
    private javax.swing.JLabel sevenButton;
    private javax.swing.JLabel sevenText;
    private javax.swing.JLabel sixButton;
    private javax.swing.JLabel sixText;
    private javax.swing.JLabel threeButton;
    private javax.swing.JLabel threeText;
    private javax.swing.JLabel twoButton;
    private javax.swing.JLabel twoText;
    private javax.swing.JLabel zeroButton;
    private javax.swing.JLabel zeroText;
    // End of variables declaration//GEN-END:variables

    private void mulAndDiv(Stack<Integer> nums, Stack<Character> sign) {
        int temp = nums.pop ();
        char tempSign = sign.pop ();

        if (tempSign == '*')
        {
                temp = nums.pop () * temp;
        }
        else if (tempSign == '/')
        {
                temp = nums.pop () / temp;
        }
        nums.add (temp);
    }

    private void sumsAndSubs(Stack<Integer> nums, Stack<Character> signs) {
        int temp;
        char sign;
        Stack <Character> invSigns = new Stack <> ();
        Stack <Integer> invNums = new Stack <> ();
        while (!signs.isEmpty ())
        {
                invSigns.add (signs.pop ());
        }
        while (!nums.isEmpty ())
        {
                invNums.add (nums.pop ());
        }
        while (!invSigns.isEmpty ())
        {
                temp = invNums.pop ();
                sign = invSigns.pop ();
                if (sign == '-')
                {
                        temp = temp - invNums.pop ();
                }
                else if (sign == '+')
                {
                        temp = temp + invNums.pop ();
                }
                invNums.add (temp);
                System.out.println (temp);
        }
        nums.add (invNums.pop ());
    }

    private void convTempNum(Stack<Integer> tempNum, Stack<Integer> nums) {
        int ith = 0;
        int num = 0;
        while (!tempNum.isEmpty ())
        {
                num += tempNum.pop () * Math.pow (10, ith++);
        }
        nums.add (num);
    }
}
